spring:
  datasource:
    url: jdbc:mysql://localhost:3306/morpiondb
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: root
    baseline-description: "init"
    baseline-version: 1

logging:
  level:
    root: INFO
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5